"""add_status_to_user_books

Revision ID: 0724d4774c90
Revises: f9afd3553347
Create Date: 2026-05-22 11:57:32.954972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0724d4774c90'
down_revision: Union[str, Sequence[str], None] = 'f9afd3553347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='unread', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'status')
    # ### end Alembic commands ###
